# Generated by Django 5.1.2 on 2024-10-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('tel_phone', models.CharField(max_length=11)),
                ('pwd', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
